site_name: pytest-aissert
site_description: Use aissert tests within pytest
site_author: Javier Torres

theme: readthedocs

repo_url: https://github.com/javiermtorres/pytest-aissert

pages:
- Home: index.md
